let
    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZZXNUus4EIVfxcVaqdK/7GUSIAOFwWWn2NxiIYgHNOVYKSeZxX2bO7OaBSvmDfxit1uyIQ4blWOnP7X6dB/9+HExf+nqC3IxX8JSOp8sOtu+ePgxy0hmuKQUn7UhKaMs/FiU8+rmLsQksyTEPxEANfbV2z2+x4+5fald/xFBWmUZFfgsFDGSasYmoDsEDfGBtbU7ix+KSLK7/hc8UUIlNZIjSDFClRFGTUAFgrbh7wPnp29jUnlAtfa4D3kQmnGmdDgccDWVIpug8oiK8Qhb2DeHSS3msFS2+dtufIfxjEOlJI+VEilRbCjbJ2wxB1iMR9Kyth2SllewXPvuYJv6p41pGa4kTUcSF5rJU9LyCkgYP5zw0u0PnTv45Lre1J1t4C+X1xjQ2X3/3oSEZwyKnkoRE5SGZDQ9k/LyGrDfWLjB1X7nwsvKtgfsi6sKlkd36D+6SOeUCM6G40v4ITIxpV9VQAdQ/35CQvjKuyDO6gEX7/p/2iFjTXRKOQ+FkBnhSkslTpmrB2BiyK+oTg4lbd8sZpgHgfp/fXJ37N+D3BxKaUQmA04SAXpn/BSXo0KRAYEDEXJddX6/D9A1Vv/o7HNoRayp0kaL0NVKE2oUpZMM83VAfkHOoMkGSnFExXIs6dJud/jJtpt6KKvUXMeyKkk0TfW0rHk13WAEhn0ctG2yAhkdFiBfYWDd+OQP3zno6UPYg8GMc2EG6QTJhD6TLl/hHqcwpBexf4t5pPb/bQONSKVEGioioXmpYnLSvAUWufjsXaS45wBawHLrUbKihpOEHjCE6RSqGmZBklQLYyaaFYuIs/37s/0ktgFYBrWg3eIGM66IZIJnZmwobbIwZl+0cqC1Y3p119rt8zG4YYGjWtYv7s9QuBQcQzAtx9wMY1P7KHBOTwgB6OzR4bcbWNZ1V+9dSHamwIwYi1MvOTgtO5v64gZpEN6/BxIa9aZObm1buw7TK28H+568nXFwJsbYp74cLHOqb3kL5LPAcYfYi9hV9+BReO7yHpZ7ewg+A2mngjKuBl8HD0iZmcDvB/g56fsOcRBKHIQC/uLhOqhfw800E2DPSFaD7YMrqFRP9qm+7TPOQenbjY+mUj58wh/r5s1HHY3M4iUy09D/jGo+uVFKtBmE9P+3g3uXHtp2G4jYZQtvk0dwTnwB2nHG4gTAraINz9KJJ5RlwEUAwtALbbKEknaxGSq8iK8bmFJoxI+db1w0MENUhhYzDpfMzpSs8DY+w8UdYKjsscHzVsXojOObGRfAMobFwQDbFUZPp7bCS/UkKEDr7tXtUJ4KB2PewR391zGYACWZlJJlQToDc5JRPhm0CkdjBCBs7V8gbdfiQddBJNtsw72ANJbKr2MLIc6OvUaBvghPT78B", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ESTADO = _t, UF = _t, CAPITAL = _t, LATITUDE = _t, LONGITUDE = _t, PAIS = _t, ESTADO_UF = _t]),
    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"LATITUDE", type number}, {"LONGITUDE", type number}}),
    Arredondado = Table.TransformColumns(#"Tipo Alterado",{{"LATITUDE", each Number.Round(_, 6), type number}, {"LONGITUDE", each Number.Round(_, 6), type number}})
in
    Arredondado
